@echo off
setlocal

set ZIP_NAME=kiosk-tab-rotator.zip

:: Delete old build if it exists
if exist "%ZIP_NAME%" del "%ZIP_NAME%"

:: Check required files exist
set MISSING=0
for %%f in (manifest.json background.js popup.html popup.js kiosk_icon_128.png icon_48.png icon_16.png) do (
    if not exist "%%f" (
        echo ERROR: Missing required file: %%f
        set MISSING=1
    )
)
if %MISSING%==1 (
    echo.
    echo Fix missing files before building. Icon files can be generated by opening generate-assets.html in Chrome.
    exit /b 1
)

:: Create zip using PowerShell (available on Windows 10+)
powershell -NoProfile -Command "Compress-Archive -Path 'manifest.json','background.js','popup.html','popup.js','kiosk_icon_128.png','icon_48.png','icon_16.png' -DestinationPath '%ZIP_NAME%' -Force"

if exist "%ZIP_NAME%" (
    echo.
    echo Build successful: %ZIP_NAME%
    echo Upload this file to the Chrome Web Store Developer Dashboard.
) else (
    echo.
    echo ERROR: Failed to create zip.
    exit /b 1
)
